/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartaoRouteImport } from './routes/cartao'
import { Route as InstalarRouteImport } from './routes/instalar'
import { Route as ItaboraiRouteImport } from './routes/itaborai'
import { Route as MaricaRouteImport } from './routes/marica'
import { Route as NiteroiRouteImport } from './routes/niteroi'
import { Route as OrcamentoRouteImport } from './routes/orcamento'
import { Route as SaoGoncaloRouteImport } from './routes/sao-goncalo'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RioDeJaneiroCentroRouteImport } from './routes/rio-de-janeiro/centro'
import { Route as RioDeJaneiroZonaSulRouteImport } from './routes/rio-de-janeiro/zona-sul'
import { Route as ServicosEletricaRouteImport } from './routes/servicos/eletrica'
import { Route as ServicosHidraulicaRouteImport } from './routes/servicos/hidraulica'
import { Route as ServicosInstalacaoChuveiroRouteImport } from './routes/servicos/instalacao-chuveiro'
import { Route as ServicosInstalacaoVentiladorRouteImport } from './routes/servicos/instalacao-ventilador'
import { Route as ServicosInstalacoesRouteImport } from './routes/servicos/instalacoes'
import { Route as ServicosJardimQuintalRouteImport } from './routes/servicos/jardim-quintal'
import { Route as ServicosMontagemRouteImport } from './routes/servicos/montagem'
import { Route as ServicosMontagemMoveisRouteImport } from './routes/servicos/montagem-moveis'
import { Route as ServicosPacotesRouteImport } from './routes/servicos/pacotes'
import { Route as ServicosPequenosReparosRouteImport } from './routes/servicos/pequenos-reparos'
import { Route as ServicosPiscinaRouteImport } from './routes/servicos/piscina'
import { Route as ServicosPrateleirasCortinasRouteImport } from './routes/servicos/prateleiras-cortinas'
import { Route as ServicosReparosHidraulicosRouteImport } from './routes/servicos/reparos-hidraulicos'
import { Route as ServicosSuporteTvRouteImport } from './routes/servicos/suporte-tv'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartaoRoute = CartaoRouteImport.update({
  id: '/cartao',
  path: '/cartao',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalarRoute = InstalarRouteImport.update({
  id: '/instalar',
  path: '/instalar',
  getParentRoute: () => rootRouteImport,
} as any)
const ItaboraiRoute = ItaboraiRouteImport.update({
  id: '/itaborai',
  path: '/itaborai',
  getParentRoute: () => rootRouteImport,
} as any)
const MaricaRoute = MaricaRouteImport.update({
  id: '/marica',
  path: '/marica',
  getParentRoute: () => rootRouteImport,
} as any)
const NiteroiRoute = NiteroiRouteImport.update({
  id: '/niteroi',
  path: '/niteroi',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoRoute = OrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const SaoGoncaloRoute = SaoGoncaloRouteImport.update({
  id: '/sao-goncalo',
  path: '/sao-goncalo',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RioDeJaneiroCentroRoute = RioDeJaneiroCentroRouteImport.update({
  id: '/rio-de-janeiro/centro',
  path: '/rio-de-janeiro/centro',
  getParentRoute: () => rootRouteImport,
} as any)
const RioDeJaneiroZonaSulRoute = RioDeJaneiroZonaSulRouteImport.update({
  id: '/rio-de-janeiro/zona-sul',
  path: '/rio-de-janeiro/zona-sul',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosEletricaRoute = ServicosEletricaRouteImport.update({
  id: '/servicos/eletrica',
  path: '/servicos/eletrica',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosHidraulicaRoute = ServicosHidraulicaRouteImport.update({
  id: '/servicos/hidraulica',
  path: '/servicos/hidraulica',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosInstalacaoChuveiroRoute =
  ServicosInstalacaoChuveiroRouteImport.update({
    id: '/servicos/instalacao-chuveiro',
    path: '/servicos/instalacao-chuveiro',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosInstalacaoVentiladorRoute =
  ServicosInstalacaoVentiladorRouteImport.update({
    id: '/servicos/instalacao-ventilador',
    path: '/servicos/instalacao-ventilador',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosInstalacoesRoute = ServicosInstalacoesRouteImport.update({
  id: '/servicos/instalacoes',
  path: '/servicos/instalacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosJardimQuintalRoute = ServicosJardimQuintalRouteImport.update({
  id: '/servicos/jardim-quintal',
  path: '/servicos/jardim-quintal',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosMontagemRoute = ServicosMontagemRouteImport.update({
  id: '/servicos/montagem',
  path: '/servicos/montagem',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosMontagemMoveisRoute = ServicosMontagemMoveisRouteImport.update({
  id: '/servicos/montagem-moveis',
  path: '/servicos/montagem-moveis',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosPacotesRoute = ServicosPacotesRouteImport.update({
  id: '/servicos/pacotes',
  path: '/servicos/pacotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosPequenosReparosRoute = ServicosPequenosReparosRouteImport.update({
  id: '/servicos/pequenos-reparos',
  path: '/servicos/pequenos-reparos',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosPiscinaRoute = ServicosPiscinaRouteImport.update({
  id: '/servicos/piscina',
  path: '/servicos/piscina',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosPrateleirasCortinasRoute =
  ServicosPrateleirasCortinasRouteImport.update({
    id: '/servicos/prateleiras-cortinas',
    path: '/servicos/prateleiras-cortinas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosReparosHidraulicosRoute =
  ServicosReparosHidraulicosRouteImport.update({
    id: '/servicos/reparos-hidraulicos',
    path: '/servicos/reparos-hidraulicos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosSuporteTvRoute = ServicosSuporteTvRouteImport.update({
  id: '/servicos/suporte-tv',
  path: '/servicos/suporte-tv',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cartao': typeof CartaoRoute
  '/instalar': typeof InstalarRoute
  '/itaborai': typeof ItaboraiRoute
  '/marica': typeof MaricaRoute
  '/niteroi': typeof NiteroiRoute
  '/orcamento': typeof OrcamentoRoute
  '/sao-goncalo': typeof SaoGoncaloRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/rio-de-janeiro/centro': typeof RioDeJaneiroCentroRoute
  '/rio-de-janeiro/zona-sul': typeof RioDeJaneiroZonaSulRoute
  '/servicos/eletrica': typeof ServicosEletricaRoute
  '/servicos/hidraulica': typeof ServicosHidraulicaRoute
  '/servicos/instalacao-chuveiro': typeof ServicosInstalacaoChuveiroRoute
  '/servicos/instalacao-ventilador': typeof ServicosInstalacaoVentiladorRoute
  '/servicos/instalacoes': typeof ServicosInstalacoesRoute
  '/servicos/jardim-quintal': typeof ServicosJardimQuintalRoute
  '/servicos/montagem': typeof ServicosMontagemRoute
  '/servicos/montagem-moveis': typeof ServicosMontagemMoveisRoute
  '/servicos/pacotes': typeof ServicosPacotesRoute
  '/servicos/pequenos-reparos': typeof ServicosPequenosReparosRoute
  '/servicos/piscina': typeof ServicosPiscinaRoute
  '/servicos/prateleiras-cortinas': typeof ServicosPrateleirasCortinasRoute
  '/servicos/reparos-hidraulicos': typeof ServicosReparosHidraulicosRoute
  '/servicos/suporte-tv': typeof ServicosSuporteTvRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cartao': typeof CartaoRoute
  '/instalar': typeof InstalarRoute
  '/itaborai': typeof ItaboraiRoute
  '/marica': typeof MaricaRoute
  '/niteroi': typeof NiteroiRoute
  '/orcamento': typeof OrcamentoRoute
  '/sao-goncalo': typeof SaoGoncaloRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/rio-de-janeiro/centro': typeof RioDeJaneiroCentroRoute
  '/rio-de-janeiro/zona-sul': typeof RioDeJaneiroZonaSulRoute
  '/servicos/eletrica': typeof ServicosEletricaRoute
  '/servicos/hidraulica': typeof ServicosHidraulicaRoute
  '/servicos/instalacao-chuveiro': typeof ServicosInstalacaoChuveiroRoute
  '/servicos/instalacao-ventilador': typeof ServicosInstalacaoVentiladorRoute
  '/servicos/instalacoes': typeof ServicosInstalacoesRoute
  '/servicos/jardim-quintal': typeof ServicosJardimQuintalRoute
  '/servicos/montagem': typeof ServicosMontagemRoute
  '/servicos/montagem-moveis': typeof ServicosMontagemMoveisRoute
  '/servicos/pacotes': typeof ServicosPacotesRoute
  '/servicos/pequenos-reparos': typeof ServicosPequenosReparosRoute
  '/servicos/piscina': typeof ServicosPiscinaRoute
  '/servicos/prateleiras-cortinas': typeof ServicosPrateleirasCortinasRoute
  '/servicos/reparos-hidraulicos': typeof ServicosReparosHidraulicosRoute
  '/servicos/suporte-tv': typeof ServicosSuporteTvRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cartao': typeof CartaoRoute
  '/instalar': typeof InstalarRoute
  '/itaborai': typeof ItaboraiRoute
  '/marica': typeof MaricaRoute
  '/niteroi': typeof NiteroiRoute
  '/orcamento': typeof OrcamentoRoute
  '/sao-goncalo': typeof SaoGoncaloRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/rio-de-janeiro/centro': typeof RioDeJaneiroCentroRoute
  '/rio-de-janeiro/zona-sul': typeof RioDeJaneiroZonaSulRoute
  '/servicos/eletrica': typeof ServicosEletricaRoute
  '/servicos/hidraulica': typeof ServicosHidraulicaRoute
  '/servicos/instalacao-chuveiro': typeof ServicosInstalacaoChuveiroRoute
  '/servicos/instalacao-ventilador': typeof ServicosInstalacaoVentiladorRoute
  '/servicos/instalacoes': typeof ServicosInstalacoesRoute
  '/servicos/jardim-quintal': typeof ServicosJardimQuintalRoute
  '/servicos/montagem': typeof ServicosMontagemRoute
  '/servicos/montagem-moveis': typeof ServicosMontagemMoveisRoute
  '/servicos/pacotes': typeof ServicosPacotesRoute
  '/servicos/pequenos-reparos': typeof ServicosPequenosReparosRoute
  '/servicos/piscina': typeof ServicosPiscinaRoute
  '/servicos/prateleiras-cortinas': typeof ServicosPrateleirasCortinasRoute
  '/servicos/reparos-hidraulicos': typeof ServicosReparosHidraulicosRoute
  '/servicos/suporte-tv': typeof ServicosSuporteTvRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cartao'
    | '/instalar'
    | '/itaborai'
    | '/marica'
    | '/niteroi'
    | '/orcamento'
    | '/sao-goncalo'
    | '/sitemap.xml'
    | '/rio-de-janeiro/centro'
    | '/rio-de-janeiro/zona-sul'
    | '/servicos/eletrica'
    | '/servicos/hidraulica'
    | '/servicos/instalacao-chuveiro'
    | '/servicos/instalacao-ventilador'
    | '/servicos/instalacoes'
    | '/servicos/jardim-quintal'
    | '/servicos/montagem'
    | '/servicos/montagem-moveis'
    | '/servicos/pacotes'
    | '/servicos/pequenos-reparos'
    | '/servicos/piscina'
    | '/servicos/prateleiras-cortinas'
    | '/servicos/reparos-hidraulicos'
    | '/servicos/suporte-tv'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cartao'
    | '/instalar'
    | '/itaborai'
    | '/marica'
    | '/niteroi'
    | '/orcamento'
    | '/sao-goncalo'
    | '/sitemap.xml'
    | '/rio-de-janeiro/centro'
    | '/rio-de-janeiro/zona-sul'
    | '/servicos/eletrica'
    | '/servicos/hidraulica'
    | '/servicos/instalacao-chuveiro'
    | '/servicos/instalacao-ventilador'
    | '/servicos/instalacoes'
    | '/servicos/jardim-quintal'
    | '/servicos/montagem'
    | '/servicos/montagem-moveis'
    | '/servicos/pacotes'
    | '/servicos/pequenos-reparos'
    | '/servicos/piscina'
    | '/servicos/prateleiras-cortinas'
    | '/servicos/reparos-hidraulicos'
    | '/servicos/suporte-tv'
  id:
    | '__root__'
    | '/'
    | '/cartao'
    | '/instalar'
    | '/itaborai'
    | '/marica'
    | '/niteroi'
    | '/orcamento'
    | '/sao-goncalo'
    | '/sitemap.xml'
    | '/rio-de-janeiro/centro'
    | '/rio-de-janeiro/zona-sul'
    | '/servicos/eletrica'
    | '/servicos/hidraulica'
    | '/servicos/instalacao-chuveiro'
    | '/servicos/instalacao-ventilador'
    | '/servicos/instalacoes'
    | '/servicos/jardim-quintal'
    | '/servicos/montagem'
    | '/servicos/montagem-moveis'
    | '/servicos/pacotes'
    | '/servicos/pequenos-reparos'
    | '/servicos/piscina'
    | '/servicos/prateleiras-cortinas'
    | '/servicos/reparos-hidraulicos'
    | '/servicos/suporte-tv'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartaoRoute: typeof CartaoRoute
  InstalarRoute: typeof InstalarRoute
  ItaboraiRoute: typeof ItaboraiRoute
  MaricaRoute: typeof MaricaRoute
  NiteroiRoute: typeof NiteroiRoute
  OrcamentoRoute: typeof OrcamentoRoute
  SaoGoncaloRoute: typeof SaoGoncaloRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  RioDeJaneiroCentroRoute: typeof RioDeJaneiroCentroRoute
  RioDeJaneiroZonaSulRoute: typeof RioDeJaneiroZonaSulRoute
  ServicosEletricaRoute: typeof ServicosEletricaRoute
  ServicosHidraulicaRoute: typeof ServicosHidraulicaRoute
  ServicosInstalacaoChuveiroRoute: typeof ServicosInstalacaoChuveiroRoute
  ServicosInstalacaoVentiladorRoute: typeof ServicosInstalacaoVentiladorRoute
  ServicosInstalacoesRoute: typeof ServicosInstalacoesRoute
  ServicosJardimQuintalRoute: typeof ServicosJardimQuintalRoute
  ServicosMontagemRoute: typeof ServicosMontagemRoute
  ServicosMontagemMoveisRoute: typeof ServicosMontagemMoveisRoute
  ServicosPacotesRoute: typeof ServicosPacotesRoute
  ServicosPequenosReparosRoute: typeof ServicosPequenosReparosRoute
  ServicosPiscinaRoute: typeof ServicosPiscinaRoute
  ServicosPrateleirasCortinasRoute: typeof ServicosPrateleirasCortinasRoute
  ServicosReparosHidraulicosRoute: typeof ServicosReparosHidraulicosRoute
  ServicosSuporteTvRoute: typeof ServicosSuporteTvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartao': {
      id: '/cartao'
      path: '/cartao'
      fullPath: '/cartao'
      preLoaderRoute: typeof CartaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalar': {
      id: '/instalar'
      path: '/instalar'
      fullPath: '/instalar'
      preLoaderRoute: typeof InstalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itaborai': {
      id: '/itaborai'
      path: '/itaborai'
      fullPath: '/itaborai'
      preLoaderRoute: typeof ItaboraiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marica': {
      id: '/marica'
      path: '/marica'
      fullPath: '/marica'
      preLoaderRoute: typeof MaricaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/niteroi': {
      id: '/niteroi'
      path: '/niteroi'
      fullPath: '/niteroi'
      preLoaderRoute: typeof NiteroiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento': {
      id: '/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof OrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sao-goncalo': {
      id: '/sao-goncalo'
      path: '/sao-goncalo'
      fullPath: '/sao-goncalo'
      preLoaderRoute: typeof SaoGoncaloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rio-de-janeiro/centro': {
      id: '/rio-de-janeiro/centro'
      path: '/rio-de-janeiro/centro'
      fullPath: '/rio-de-janeiro/centro'
      preLoaderRoute: typeof RioDeJaneiroCentroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rio-de-janeiro/zona-sul': {
      id: '/rio-de-janeiro/zona-sul'
      path: '/rio-de-janeiro/zona-sul'
      fullPath: '/rio-de-janeiro/zona-sul'
      preLoaderRoute: typeof RioDeJaneiroZonaSulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/eletrica': {
      id: '/servicos/eletrica'
      path: '/servicos/eletrica'
      fullPath: '/servicos/eletrica'
      preLoaderRoute: typeof ServicosEletricaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/hidraulica': {
      id: '/servicos/hidraulica'
      path: '/servicos/hidraulica'
      fullPath: '/servicos/hidraulica'
      preLoaderRoute: typeof ServicosHidraulicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/instalacao-chuveiro': {
      id: '/servicos/instalacao-chuveiro'
      path: '/servicos/instalacao-chuveiro'
      fullPath: '/servicos/instalacao-chuveiro'
      preLoaderRoute: typeof ServicosInstalacaoChuveiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/instalacao-ventilador': {
      id: '/servicos/instalacao-ventilador'
      path: '/servicos/instalacao-ventilador'
      fullPath: '/servicos/instalacao-ventilador'
      preLoaderRoute: typeof ServicosInstalacaoVentiladorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/instalacoes': {
      id: '/servicos/instalacoes'
      path: '/servicos/instalacoes'
      fullPath: '/servicos/instalacoes'
      preLoaderRoute: typeof ServicosInstalacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/jardim-quintal': {
      id: '/servicos/jardim-quintal'
      path: '/servicos/jardim-quintal'
      fullPath: '/servicos/jardim-quintal'
      preLoaderRoute: typeof ServicosJardimQuintalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/montagem': {
      id: '/servicos/montagem'
      path: '/servicos/montagem'
      fullPath: '/servicos/montagem'
      preLoaderRoute: typeof ServicosMontagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/montagem-moveis': {
      id: '/servicos/montagem-moveis'
      path: '/servicos/montagem-moveis'
      fullPath: '/servicos/montagem-moveis'
      preLoaderRoute: typeof ServicosMontagemMoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/pacotes': {
      id: '/servicos/pacotes'
      path: '/servicos/pacotes'
      fullPath: '/servicos/pacotes'
      preLoaderRoute: typeof ServicosPacotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/pequenos-reparos': {
      id: '/servicos/pequenos-reparos'
      path: '/servicos/pequenos-reparos'
      fullPath: '/servicos/pequenos-reparos'
      preLoaderRoute: typeof ServicosPequenosReparosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/piscina': {
      id: '/servicos/piscina'
      path: '/servicos/piscina'
      fullPath: '/servicos/piscina'
      preLoaderRoute: typeof ServicosPiscinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/prateleiras-cortinas': {
      id: '/servicos/prateleiras-cortinas'
      path: '/servicos/prateleiras-cortinas'
      fullPath: '/servicos/prateleiras-cortinas'
      preLoaderRoute: typeof ServicosPrateleirasCortinasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/reparos-hidraulicos': {
      id: '/servicos/reparos-hidraulicos'
      path: '/servicos/reparos-hidraulicos'
      fullPath: '/servicos/reparos-hidraulicos'
      preLoaderRoute: typeof ServicosReparosHidraulicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/suporte-tv': {
      id: '/servicos/suporte-tv'
      path: '/servicos/suporte-tv'
      fullPath: '/servicos/suporte-tv'
      preLoaderRoute: typeof ServicosSuporteTvRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartaoRoute: CartaoRoute,
  InstalarRoute: InstalarRoute,
  ItaboraiRoute: ItaboraiRoute,
  MaricaRoute: MaricaRoute,
  NiteroiRoute: NiteroiRoute,
  OrcamentoRoute: OrcamentoRoute,
  SaoGoncaloRoute: SaoGoncaloRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  RioDeJaneiroCentroRoute: RioDeJaneiroCentroRoute,
  RioDeJaneiroZonaSulRoute: RioDeJaneiroZonaSulRoute,
  ServicosEletricaRoute: ServicosEletricaRoute,
  ServicosHidraulicaRoute: ServicosHidraulicaRoute,
  ServicosInstalacaoChuveiroRoute: ServicosInstalacaoChuveiroRoute,
  ServicosInstalacaoVentiladorRoute: ServicosInstalacaoVentiladorRoute,
  ServicosInstalacoesRoute: ServicosInstalacoesRoute,
  ServicosJardimQuintalRoute: ServicosJardimQuintalRoute,
  ServicosMontagemRoute: ServicosMontagemRoute,
  ServicosMontagemMoveisRoute: ServicosMontagemMoveisRoute,
  ServicosPacotesRoute: ServicosPacotesRoute,
  ServicosPequenosReparosRoute: ServicosPequenosReparosRoute,
  ServicosPiscinaRoute: ServicosPiscinaRoute,
  ServicosPrateleirasCortinasRoute: ServicosPrateleirasCortinasRoute,
  ServicosReparosHidraulicosRoute: ServicosReparosHidraulicosRoute,
  ServicosSuporteTvRoute: ServicosSuporteTvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
